In [2]:
import numpy as np
import pandas as pd

In [ ]:
array=[1,2,3]

In [ ]:
vector = np.array(array)

In [ ]:
print(" Vector   : " + str(vector))

 Vector   : [1 2 3]


In [ ]:
x=np.mean(vector)
x

2.0

In [ ]:
z=np.subtract(array,x)
z

array([-1.,  0.,  1.])

In [ ]:
j=z**2
j

array([1., 0., 1.])

In [ ]:
k=np.sum(j)
k

2.0

In [ ]:
samplevariance = k/(3-1)
print("samplevariance = " + str(samplevariance))


samplevariance = 1.0


In [ ]:
populationvariance = k/3
print("populationvariance = " + str(populationvariance))


populationvariance = 0.6666666666666666


In [ ]:
x=[3,2,1]
y=[4,5,6]


In [ ]:
vectorx = np.array(x)

In [ ]:
vectory = np.array(y)

In [ ]:
print(" Vector x  : " + str(vectorx))
print(" Vector y : " + str(vectory))

 Vector x  : [3 2 1]
 Vector y : [4 5 6]


In [ ]:
x=np.mean(vectorx)
x


2.0

In [ ]:
y=np.mean(vectory)
y

5.0

In [ ]:
x=np.subtract(vectorx,x)
x

array([ 1.,  0., -1.])

In [ ]:
y=np.subtract(vectory,y)
y

array([-1.,  0.,  1.])

In [ ]:
g=x*y
g

array([-1.,  0., -1.])

In [ ]:
d=sum(g)
d

-2.0

In [ ]:
covaraince=d/(3-1)
print("covariance of x and y = " + str(covaraince))

covariance of x and y = -1.0


In [ ]:
varx=np.var(x)
varx


0.6666666666666666

In [ ]:
vary=np.var(y)
vary

0.6666666666666666

In [ ]:
h=(varx*vary)**(1/2)
h

0.6666666666666666

In [ ]:
correlation=covaraince/h
print("correlation of x and y = " + str(correlation))


correlation of x and y = -1.5


In [3]:
j=[[4,5,6],[1,2,3]]
j=np.array(j)

In [4]:
covmatrix=np.cov(j)
print("covariance matrix:\n",covmatrix,"\n")

covariance matrix:
 [[1. 1.]
 [1. 1.]] 



In [6]:
corelationmatrix = np.corrcoef(j)
print("correlation matrix:\n",corelationmatrix)

correlation matrix:
 [[1. 1.]
 [1. 1.]]
